### ISSUE TITLE
Activity / Notifications Evolution

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/apps#1704]
ToDo:
- [x] Issue #1705 / PR #1718 **Implement settings page**

```
Activity                                    | Mail | Stream
--------------------------------------------+------+----------
Someone shares a folder with you            | [x]  | [x] // Notify me please
Someone uploads a file into a shared folder | [ ]  | [x] // Not that important, let me see it in my stream
Someone changes a file in a shared folder   | [ ]  | [ ] // I don't even care ;)
```
- [x] PR #1718 Respect **setting for stream**
  We should not list activities the user selected he does not want to see anymore
- [ ] Issue #1669 / PR #1743 **Send a mail** to the user if he has activities matching his mail notification setting
  We could allow the user to select the grouping by himself: Options I have in mind are:
  - Daily
  - Hourly
  - Immediately
- [ ] Issue #1670 **Enhance list of available activities**

Additional thoughts? cc @jancborchardt @karlitschek
